src/Entity/DetailCommande.php
<?php
namespace Entity;

/**
 * Description of DetailCommande
 *
 * @author Julien
 */
class DetailCommande 
{
    /**
     * @var int
     */
    private $id_detail_commande;
    
    private $commande_id;
    
    private $produit_id;
    
    private $custom_id;
    
    /**
     * @var Commande
     */
    private $commande;
    
    /**
     * @var Produit
     */
    private $produit;
    
    /**
     * @var Custom
     */
    private $custom;
    
    /**
     * @var int
     */
    private $quantite;
    
    /**
     * @var int
     */
    private $prix;
    
    
    
    public function getCommande_id() {
        return $this->commande_id;
    }

    public function getProduit_id() {
        return $this->produit_id;
    }

    public function getCustom_id() {
        return $this->custom_id;
    }

    /**
     * @return int
     */
    public function getId_detail_commande() {
        return $this->id_detail_commande;
    }

    /**
    * @return int
    */
    public function getCommande() {
        return $this->commande;
    }

    /**
    * @return int
    */
    public function getProduit() {
        return $this->produit;
    }

    /**
    * @return int
    */
    public function getCustom() {
        return $this->custom;
    }

    /**
    * @return int
    */
    public function getQuantite() {
        return $this->quantite;
    }

    /**
    * @return int
    */
    public function getPrix() {
        return $this->prix;
    }

    /**
     * @param int $id_detail_commande
     * @return DetailCommande
     */
    public function setId_detail_commande($id_detail_commande) {
        $this->id_detail_commande = $id_detail_commande;
        return $this;
    }

    /**
     * @param Commande $commande
     * @return DetailCommande
     */
    public function setCommande(Commande $commande) {
        $this->commande = $commande;
        return $this;
    }

    /**
     * @param Produit $produit
     * @return DetailCommande
     */
    public function setProduit(Produit $produit) {
        $this->produit = $produit;
        return $this;
    }

    /**
     * @param Custom $custom
     * @return DetailCommande
     */
    public function setCustom(Custom $custom) {
        $this->custom = $custom;
        return $this;
    }

    /**
     * @param int $quantite
     * @return DetailCommande
     */
    public function setQuantite($quantite) {
        $this->quantite = $quantite;
        return $this;
    }

    /**
     * @param int $prix
     * @return DetailCommande
     */
    public function setPrix($prix) {
        $this->prix = $prix;
        return $this;
    }

    /***** fonctions proxy *****/
    
    /**
     * return string
     */
    public function getTitreProduit(){
        if(!is_null($this->produit)){
            return $this->produit->getTitre();
        }
    }
    
    /**
     * 
     * @return int
     */
    public function getProduitId(){
        if(!is_null($this->produit)){
            return $this->produit->getId();
        }
    }
    
    /**
     * return string
     */
    public function getTitreCustom(){
        if(!is_null($this->custom)){
            return $this->custom->getTitre_custom();
        }
    }
    
    /**
     * return int
     */
    public function getCustomId(){
        if(!is_null($this->custom)){
            return $this->custom->getId_custom();
        }
    }

     /**
     * 
     * @return int
     */
    public function getCommandeId(){
        if(!is_null($this->commande)){
            return $this->commande->getId_commande();
        }
    }
    
    public function setCommande_id($commande_id) {
        $this->commande_id = $commande_id;
        return $this;
    }

    public function setProduit_id($produit_id) {
        $this->produit_id = $produit_id;
        return $this;
    }

    public function setCustom_id($custom_id) {
        $this->custom_id = $custom_id;
        return $this;
    }

    public function getTitre()
    {
        if (!empty($this->getTitreCustom())) {
            return $this->getTitreCustom();
        }
        
        return $this->getTitreProduit();
    }

}

mvc/Controller/UserController.php
<?php
namespace Controller; 


class UserController{
    
    
    public function listAction(){
        echo 'user:list';
    }
}

src/Controller/UserController.php
<?php
namespace Controller;
use Entity\User;
use Service\UserManager;
use DateTime;

class UserController extends ControllerAbstract
{
    public function registerAction(){
        $user = new User();
        $errors = [];


        if (!empty($_POST)) {
            $dateNaissance = \DateTime::createFromFormat('d/m/Y', $_POST['date_naissance']);
            if (empty($dateNaissance)) {
                $dateNaissance = new \DateTime($_POST['date_naissance']);
            }


            $user
                ->setNom($_POST['nom'])
                ->setPrenom($_POST['prenom'])
                ->setDate_naissance($dateNaissance)
                ->setEmail($_POST['email'])
                ->setPassword($_POST['password'])
                ->setAdresse($_POST['adresse'])
                ->setComplement_adresse($_POST['complement_adresse'])
                ->setCode_postal($_POST['code_postal'])
                ->setVille($_POST['ville'])
                ->setTel($_POST['tel'])
                ->setSexe($_POST['sexe'])
                ->setStatut('membre');


            if (empty($_POST['nom'])) {
                $errors['nom'] = 'Le nom est obligatoire';
            }

            if (empty($_POST['prenom'])) {
                $errors['prenom'] = 'Le prénom est obligatoire';
            }

            if (empty($_POST['date_naissance'])) {
                $errors['date_naissance'] = 'La date de naissance est obligatoire';
            }

            if (empty($_POST['email'])) {
                $errors['email'] = "L'e-mail est obligatoire";
            } elseif (!filter_var($_POST['email'], FILTER_VALIDATE_EMAIL)) {
                $errors['email'] = "L'e-mail n'est pas valide";
            } elseif (!empty($this->app['user.repository']->findByEmail($_POST['email']))) {
                $errors['email'] = 'Cet email est déjà utilisé';
            }

            if (empty($_POST['adresse'])) {
                $errors['adresse'] = "Veuillez indiquer votre adresse";
            }

            if (empty($_POST['code_postal'])) {
                $errors['code_postal'] = "Veuillez indiquer votre code postal";
            }

            if (empty($_POST['tel'])) {
                $errors['tel'] = "Veuillez indiquer votre numéro de téléphone";
            }

            if (empty($_POST['ville'])) {
                $errors['ville'] = "Veuillez indiquer votre ville";
            }

            if (empty($_POST['sexe'])) {
                $errors['sexe'] = 'Veuillez indiquer votre genre svp';
            }

            if (empty($_POST['password'])) {
                $errors['password'] = "Le mot de passe est obligatoire";
            } elseif (!preg_match('/^[a-zA-Z0-9_-]{6,20}$/', $_POST['password'])) {
                $errors['password'] = "Le mot de passe doit comprendre entre 6 et 20 caractères et ne doit contenir que des lettres, des chiffres ou les caractères _ et -";
            }

            if (empty($_POST['password_confirm'])) {
                $errors['password_confirm'] = "La confirmation du mot de passe est obligatoire";
            } elseif ($_POST['password'] != $_POST['password_confirm']) {
                $errors['password_confirm'] = "La confirmation n'est pas identique au mot de passe";
            }

            if (empty($errors)) {
                $user->setPassword($this->app['user.manager']->encodePassword($_POST['password']));
                $this->app['user.repository']->save($user);
                $this->app['user.manager']->login($user);

                return $this->redirectRoute('homepage');
            } else {
                $msg = '<strong>Le formulaire contient des erreurs</strong>';
                $msg .= '<br>' . implode('<br>', $errors);

                $this->addFlashMessage($msg, 'error');
            }
        }

        return $this->render(
            'user/register.html.twig',
            [
                'user' => $user
            ]
        );
    }
    
    public function loginAction(){
        $email = '';
        
        if(!empty($_POST)){
            $email = $_POST['email'];
            
            $user = $this->app['user.repository']->findByEmail($email);
            
            if(!is_null($user)){
                if($this->app['user.manager']->verifyPassword($_POST['password'], $user->getPassword())){
                    $this->app['user.manager']->login($user);
                
                return $this->redirectRoute('homepage');
                }
            }
            
            $this->addFlashMessage('Identification incorrecte', 'error');
        }
        
        return $this->render(
            'user/login.html.twig',
            ['email' => $email]
        );
    }
    
    public function logoutAction(){
        $this->app['user.manager']->logout();
        
        return $this->redirectRoute('homepage');
    }

    public function modifAction()
    {
        $user = $this->app['user.manager']->getUser();

        //echo'<pre>';print_r($user);echo '</pre>';

        if (!empty($_POST)) {
            $dateNaissance = \DateTime::createFromFormat('d/m/Y', $_POST['date_naissance']);

            if (empty($dateNaissance)) {
                $dateNaissance = new \DateTime($_POST['date_naissance']);
            }

            $user
                ->setPrenom($_POST['prenom'])
                ->setNom($_POST['nom'])
                ->setDate_naissance($dateNaissance)
                ->setEmail($_POST['email'])
                //->setPassword($_POST['password'])
                ->setAdresse($_POST['adresse'])
                ->setComplement_adresse($_POST['complement_adresse'])
                ->setCode_postal($_POST['code_postal'])
                ->setVille($_POST['ville'])
                ->setTel($_POST['tel'])
                ->setSexe($_POST['sexe'])
            ;




            if (empty($_POST['prenom'])) {
                $errors['prenom'] = 'Le nom est obligatoire';
            }

            if (empty($_POST['nom'])) {
                $errors['nom'] = 'Le prénom est obligatoire';
            }

           if (empty($_POST['date_naissance'])) {
               $errors['date_naissance'] = 'La date de naissance est obligatoire';
            }


            if (empty($_POST['adresse'])) {
                $errors['adresse'] = "Veuillez indiquer votre adresse";
            }

            if (empty($_POST['code_postal'])) {
                $errors['code_postal'] = 'Veuillez indiquer votre code postal';
            }

            if (empty($_POST['ville'])) {
                $errors['ville'] = 'Veuillez indiquer votre ville';
            }

            if (empty($_POST['tel'])) {
                $errors['tel'] = 'Veuillez indiquer votre numéro de téléphone svp';
            }

            if (empty($_POST['sexe'])) {
                $errors['sexe'] = 'Veuillez indiquer votre genre svp';
            }


            if (empty($errors)) {
                if (!empty($_POST['password'])) {
                    $user->setPassword($this->app['user.manager']->encodePassword($_POST['password']));
                }
                $this->app['user.repository']->save($user);
                return $this->redirectRoute('profile');

            } else {
                $msg = '<strong>Le formulaire contient des erreurs</strong>';
                $msg .= '<br>' . implode('<br>', $errors);

                $this->addFlashMessage($msg, 'error');
            }
        }

        return $this->render(
            'user/modif.html.twig',
            [
                'user' => $user
            ]
        );
    }

    // méthode créée par Julien pour afficher les commandes d'un utilisateur
    public function showProfile(){
        // je récupère l'utilisateur connecté
        $user = $this->app['user.manager']->getUser();
        
        // je récupère toutes les commandes de l'utilisateur
        $commandes = $this->app['commande.repository']->findAllByUser($user);
        
        // je déclare un tableau pour stocker les détails de chaque commande
        //$details_commandes =[];
        //$detailsCommandes = [];
        //$customs = [];
        //$produits = [];
        
        // je boucle sur les commandes pour récupérer les détails associés
        foreach($commandes as $commande){

            $detailsCommande = $this->app['detail.commande.repository']->findAllByCommande($commande->getId_commande());
            
            foreach ($detailsCommande as $detailCommande) {
               
                if(!is_null($detailCommande->getCustom_id())){
                  
                    $custom = $this->app['custom.repository']->find($detailCommande->getCustom_id());
                   
                    $detailCommande->setCustom($custom);
                }else{
                    $produit = $this->app['produit.repository']->findById($detailCommande->getProduit_Id());
                    $detailCommande->setProduit($produit);
                } 
            }
            
            $commande->setDetails($detailsCommande);
            
            //echo '<pre>'; var_dump($detailsCommandes); echo '</pre>';
            //$details_commandes[] = $detailsCurrentCommande;
            //echo '<pre>'; var_dump($customs); echo '</pre>';
        }
        
        
        //echo '<pre>'; var_dump($detailsCommandes); echo '</pre>';

        return $this->render(
        'user/profile.html.twig',
            [
                'user' => $user,
                'commandes' => $commandes,
          //      'customs' => $customs,
            //    'produit' => $produit,
              //  'detailsCommandes' => $detailsCommandes
            ]        
        );

    }



    public function showAllUsers()
    {

        $users = $this->app['user.repository']->findAllByUsers();
        return $this->render(
            'admin/user/panel.html.twig',
            ['users' => $users]

        );

    }

    public function AdminModifAction($id_user)
    {

templates/user/login.html.twig
{% extends "layout.html.twig" %}

{% block title 'Connexion' %}

{% block content %}
<h1>Connexion</h1>
    <form method="post">
        <div class="form-group">
            <label>Email</label>
            <input type="text" name="email" value="{{ email }}" class="form-control">
        </div>
        <div class="form-group">
            <label>Mot de passe</label>
            <input type="password" name="password" class="form-control">
        </div>
        
        <button type="submit" class="btn btn-primary"> 
            Se connecter
        </button>
        <a href=''>Mot de passe oublié ?</a>
    </form>
    <br>
    <a href='{{ path('register') }}'>Pas encore de compte ? Accédez au formulaire d'inscription en cliquant sur ce lien.</a>
 {% endblock %}

templates/user/modif.html.twig
{% extends "layout.html.twig" %}

{% block title "Modification de votre profil" %}


{% block content %}
    <h1>Modification de votre profil</h1>
    <div class="container">
    <div class="row">
        <div class="col-xl-12 col-sm-12 col-xs-12">
    <form method="post">
        <input type="hidden" name="id_user" value="{{ user.id_user }}">
        <div class="form-group">
            <label for="prenom">Prénom</label>
            <input type="text" name="prenom" class="form-control" id="prenom" value="{{ user.prenom }}">
        </div>

        <div class="form-group">
            <label for="nom">Nom</label>
            <input type="text" name="nom" class="form-control" id="nom" value="{{ user.nom }}">
        </div>

        <div class="form-group">
            <label for="date_naissance">Date de naissance</label>
            <input type="date" name="date_naissance" class="form-control" id="date_naissance" value={{ user.date_naissance|date('d/m/Y') }}>
        </div>

        <div class="form-group">
            <label for="email">Courriel</label>
            <input type="email" name="email" class="form-control" id="email" value="{{ user.email }}">
        </div>

        <div class="form-group">
            <label for="password">Mot de passe</label>
            <input type="password" name="password" class="form-control" id="password" value="******">
        </div>

        <div class="form-group">
            <label for="adresse">Adresse</label>
            <input type="text" name="adresse" class="form-control" id="adresse" value="{{ user.adresse }}">
        </div>

        <div class="form-group">
            <label for="complement_adresse">Complément d'adresse</label>
            <input type="text" name="complement_adresse" class="form-control" id="complement_adresse" value="{{ user.complement_adresse }}">
        </div>

        <div class="form-group">
            <label for="code_postal">Code postal</label>
            <input type="number" name="code_postal" class="form-control" id="code_postal" value="{{ user.code_postal }}">
        </div>

        <div class="form-group">
            <label for="ville">Ville</label>
            <input type="text" name="ville" class="form-control" id="ville" value="{{ user.ville }}">
        </div>

        <div class="form-group">
            <label for="tel">Téléphone</label>
            <input type="text" name="tel" class="form-control" id="tel" value="{{ user.tel }}">
        </div>


        <div class="form-group">
            <label for="">Sexe</label>
            <select name="sexe" id="sexe">
                                <option value="masculin">Masculin</option>
                <option value="feminin">Féminin</option>
                            </select>
        </div>

        <button type="submit" class="btn btn-primary" Value="Envoi">
            Enregistrer
        </button>
    </form>
            </div>
    </div>
    </div>
{% endblock %}

templates/user/profile.html.twig
{% extends "layout.html.twig" %}

{% block title 'Mon compte' %}

{% block content %}
    {% block commandes %}
        <div class="container">

            <h1>Mon compte</h1>
            <h2>Mes informations</h2>
            <table class="table">

                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Date de naissance</th>
                    <th>Email</th>
                    <th>Téléphone</th>
                    <th>Adresse</th>
                    <th>Complément d'adresse</th>
                    <th>Code postal</th>
                    <th>Ville</th>
                    <th>Sexe</th>
                    {% if user_manager.admin %}
                        <th>Statut</th>
                    {% endif %}
                    <th width="200px">Actions</th>
                </tr>
                <tr>
                    <td>{{ user.nom }}</td>
                    <td>{{ user.prenom }}</td>
                    <td>{{ user.date_naissance|date('d/m/Y') }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.tel }}</td>
                    <td>{{ user.adresse }}</td>
                    <td>{{ user.complement_adresse }}</td>
                    <td>{{ user.code_postal }}</td>
                    <td>{{ user.ville }}</td>
                    <td>{{ user.sexe }}</td>
                    <td><a href="{{ path('profile_edit') }}"><span class="glyphicon glyphicon-pencil"></span> Modifier mes infos</a></td>
                    {% if user_manager.admin %}
                        <td>{{ user.statut }}</td>
                    {% endif %}
                    <td>
                        {#<a href ="{{ path('edit_user', {id: user.id_user}) }}" class="btn btn-primary">Modifier mes informations de profil</a>
                        <a href ="{{ path('delete_user', {id: user.id_user}) }}" class="btn btn-danger">Supprimer mon profil</a>#}
                    </td>
                </tr>
                
            </table>
            
            <br>        
            <h2>Mes commandes</h2>
            <table class="table">
                <caption>Commandes</caption>
                <tr>
                    <th>Id</th>
                    <th>Prix livraison</th>
                    <th>Total</th>
                    <th>Date commande</th>
                    <th>Etat</th>
                    <th width="200px">Action</th>
                </tr>
                {% for commande in commandes %}
                    <tr class="info"><th colspan="6">Commande n°{{ commande.id_commande }}</th></tr>
                    <tr>
                        <td>{{ commande.id_commande }}</td>
                        <td>{{ commande.prix_livraison }}</td>
                        <td>{{ commande.total }}</td>
                        <td>{{ commande.date_commande|date('d/m/Y') }}</td>
                        <td>{{ commande.etat }}</td>
                        <td>
                            {% if commande.etat != 'livré' %}
                                <a href ="{#{{ path('suivi_commande', {id: commande.id_commande}) }}#}https://www.laposte.fr/particulier/outils/suivre-vos-envois" class="btn btn-primary"><span class="glyphicon glyphicon-circle-arrow-right"></span> Suivre ma commande</a>
                            {% endif %}
                            {% if commande.etat == 'en préparation' or commande.etat == 'expédié' or commande.etat == 'en livraison' %}
                                <a href ="{{ path('delete_commande', {id: commande.id_commande}) }}" class="btn btn-danger"><span class="glyphicon glyphicon-trash" ></span> Annuler ma commande</a>
                            {% elseif commande.etat == 'livré' %}
                                <a href ="{{ path('return_commande', {id: commande.id_commande}) }}" class="btn btn-warning"><span class="glyphicon glyphicon-remove-sign"></span> Retourner ma commande</a>
                            {% endif %}
                        </td>
                    </tr>
                    <tr><th colspan="6">Détail commande n°{{ commande.id_commande }}</th></tr>
                    <tr>
                        <th colspan="4">Titre</th>
                        <th colspan="1">Quantité</th>
                        <th colspan="1">Prix</th>
                    </tr>
                    
                    {% for detailCommande in commande.details %}
                        
                        {#<pre>{{ dump(detailCommande.custom) }}</pre>#}
                        <tr>
                            {% if detailCommande.custom.id_custom is null %}
                                <td colspan="4">{{ detailCommande.produit.titre }}</td>
                            {% else %}  
                                <td colspan="4">{{ detailCommande.custom.titre_custom }}</td>
                            {% endif %}
                            <td colspan="1">{{ detailCommande.quantite }}</td>
                            <td colspan="1">{{ detailCommande.prix }}</td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </table>
                </div>
            </div>
        </div>
    {% endblock %}
{% endblock %}

templates/user/register.html.twig
{% extends "layout.html.twig" %}

{% block title 'Inscription' %}

{% block content %}
    <div class="container">
        <h1>Inscription</h1>
        <form method="post">
            <div class="form-group">
                <label>Nom</label>
                <input type="text" name="nom" value="{{ user.nom }}" class="form-control">
            </div>
            <div class="form-group">
                <label>Prénom</label>
                <input type="text" name="prenom" value="{{ user.prenom }}" class="form-control">
            </div>
            <div class="form-group">
                <label>Date de naissance</label>
                <input type="date" name="date_naissance" value="{% if user.date_naissance is not null %}{{ user.date_naissance|date('d/m/Y') }}{% endif %}" class="form-control">
            </div>
            <div class="form-group">
                <label>Email</label>
                <input type="text" name="email" value="{{ user.email }}" class="form-control">
            </div>
            <div class="form-group">
                <label>Mot de passe</label>
                <input type="password" name="password" class="form-control">
            </div>
            <div class="form-group">
                <label>Confirmation du mot de passe</label>
                <input type="password" name="password_confirm" class="form-control">
            </div>
            <div class="form-group">
                <label>Adresse</label>
                <input type="text" name="adresse" value="{{ user.adresse }}" class="form-control">
            </div>
            <div class="form-group">
                <label>Complément d'adresse</label>
                <input type="text" name="complement_adresse" value="{{ user.complement_adresse }}" class="form-control">
            </div>
            <div class="form-group">
                <label>Code postal</label>
                <input type="number" name="code_postal" value="{{ user.code_postal }}" class="form-control">
            </div>
            <div class="form-group">
                <label>Ville</label>
                <input type="text" name="ville" value="{{ user.ville }}" class="form-control">
            </div>
            <div class="form-group">
                <label>Téléphone</label>
                <input type="text" name="tel" value="{{ user.tel }}" class="form-control">
            </div>
            <div class="form-group">
                <label>Sexe</label>
                <select name='sexe'>
                    <option value=''>Quel est votre sexe ?</option>
                    <option value='m'>Homme</option>
                    <option value='f'>Femme</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">
                Enregistrer
            </button>
        </form>
    </div>
{% endblock %}